package pkg.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("dish", "id", Dish.class);
		arp.addMapping("dish_rate", "id", DishRate.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_rate", "id", UserRate.class);
	}
}


