package pkg.model;

import pkg.model.base.BaseDishRate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DishRate extends BaseDishRate<DishRate> {
	public static final DishRate dao = new DishRate().dao();
}

