package pkg.model;

import pkg.model.base.BaseDish;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dish extends BaseDish<Dish> {
	public static final Dish dao = new Dish().dao();
}

