package pkg.model;

import pkg.model.base.BaseUser;

import java.util.Objects;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
    public static final User dao = new User().dao();

    @Override
    public boolean equals(Object o) {
        if(getClass() != o.getClass()) return false;
        BaseUser<User> u2 = (BaseUser<User>) o;
        return getId().equals(u2.getId()) &&
                Objects.equals(getUsername(), u2.getUsername()) &&
                Objects.equals(getPassword(), u2.getPassword()) &&
                Objects.equals(getIsManager(), u2.getIsManager()) &&
                Objects.equals(getName(), u2.getName()) &&
                Objects.equals(getAge(), u2.getAge()) &&
                Objects.equals(getAvatar(), u2.getAvatar()) &&
                Objects.equals(getGender(), u2.getGender());


    }
}

