package pkg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDishRate<M extends BaseDishRate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public void setDishId(java.lang.Long dishId) {
		set("dish_id", dishId);
	}
	
	public java.lang.Long getDishId() {
		return getLong("dish_id");
	}
	
	public void setDemand(java.lang.Integer demand) {
		set("demand", demand);
	}
	
	public java.lang.Integer getDemand() {
		return getInt("demand");
	}
	
	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return getDate("time");
	}
	
}

