package pkg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setAge(java.lang.Integer age) {
		set("age", age);
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}
	
	public void setGender(java.lang.String gender) {
		set("gender", gender);
	}
	
	public java.lang.String getGender() {
		return getStr("gender");
	}
	
	public void setIsManager(java.lang.Boolean isManager) {
		set("is_manager", isManager);
	}
	
	public java.lang.Boolean getIsManager() {
		return getBoolean("is_manager");
	}
	
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
}

